<!DOCTYPE html>
<html lang="en"><head>
<script src="ch6_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch6_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch6_files/libs/quarto-html/popper.min.js"></script>
<script src="ch6_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch6_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch6_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Yu-You Liou (NTU)">
  <meta name="dcterms.date" content="2026-06-06">
  <title>Data Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch6_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch6_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch6_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <link href="ch6_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch6_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch6_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch6_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Data Analysis</h1>
  <p class="subtitle">Chapter 6: Maps</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou (NTU) 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-06-06</p>
</section>
<section>
<section id="maps" class="title-slide slide level1 center">
<h1>Maps</h1>

</section>
<section id="maps-1" class="slide level2">
<h2>Maps</h2>
<p>Plotting geospatial data is one of the most frequently encountered visualisation tasks, and it requires tools that go beyond standard ggplot2 geoms. The challenge can be broken into two distinct sub-problems:</p>
<ol type="1">
<li><strong>Drawing the map</strong> — rendering geographic boundaries or terrain from a spatial data source.</li>
<li><strong>Overlaying metadata</strong> — projecting additional variables (e.g., population density, election results, rainfall) from a separate data source onto the rendered map.</li>
</ol>
<p>This chapter addresses both problems and is organised as follows:</p>
<ul>
<li><strong>Section 6.1</strong> — polygon-based maps with <code>geom_polygon()</code>, the simplest approach.</li>
<li><strong>Section 6.2</strong> — modern simple features (sf) maps with <code>geom_sf()</code>.</li>
<li><strong>Section 6.3</strong> — map projections and coordinate reference systems.</li>
<li><strong>Section 6.4</strong> — working programmatically with sf data structures.</li>
<li><strong>Section 6.5</strong> — raster-based maps using satellite imagery.</li>
</ul>
</section></section>
<section>
<section id="polygon-maps" class="title-slide slide level1 center">
<h1>Polygon maps</h1>

</section>
<section id="polygon-maps-1" class="slide level2">
<h2>Polygon maps</h2>
<p>The most straightforward path to drawing a map in ggplot2 is to represent geographic boundaries as ordinary polygons and render them with <code>geom_polygon()</code>. The <code>maps</code> package, bundled with R, provides boundary data accessible through <code>ggplot2::map_data()</code>.</p>
<p>The code below retrieves county-level boundaries for the state of Michigan and renames the columns for clarity:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href=""></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href=""></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-4"><a href=""></a></span>
<span id="cb1-5"><a href=""></a>mi_counties <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"county"</span>, <span class="st">"michigan"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-6"><a href=""></a>  <span class="fu">select</span>(<span class="at">lon =</span> long, lat, group, <span class="at">id =</span> subregion)</span>
<span id="cb1-7"><a href=""></a><span class="fu">head</span>(mi_counties)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        lon      lat group     id
1 -83.88675 44.85686     1 alcona
2 -83.36536 44.86832     1 alcona
3 -83.36536 44.86832     1 alcona
4 -83.33098 44.83968     1 alcona
5 -83.30806 44.80530     1 alcona
6 -83.30233 44.77665     1 alcona</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Understanding the data structure</strong></p>
<p>The returned data frame contains four variables:</p>
<ul>
<li><code>lon</code> / <code>lat</code> — longitude and latitude of each individual polygon <strong>vertex</strong> (corner point).</li>
<li><code>id</code> — the name of the county to which the vertex belongs.</li>
<li><code>group</code> — a unique integer identifying each contiguous polygon. Counties that consist of multiple separated parts (e.g., islands) require multiple group values, one per polygon.</li>
</ul>
</section>
<section class="slide level2">

<p><strong>From scatterplot to choropleth map</strong></p>
<p>Plotting the raw vertices as points with <code>geom_point()</code> produces a scatterplot of all polygon corners — a useful diagnostic step that confirms the data has been loaded correctly. Replacing <code>geom_point()</code> with <code>geom_polygon()</code> and mapping <code>group</code> connects the vertices into filled county outlines:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mi_counties, <span class="fu">aes</span>(lon, lat)) <span class="sc">+</span></span>
<span id="cb3-2"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> .<span class="dv">25</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href=""></a>  <span class="fu">coord_quickmap</span>()</span>
<span id="cb3-4"><a href=""></a></span>
<span id="cb3-5"><a href=""></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mi_counties, <span class="fu">aes</span>(lon, lat, <span class="at">group =</span> group)) <span class="sc">+</span></span>
<span id="cb3-6"><a href=""></a>  <span class="fu">geom_polygon</span>(<span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">colour =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href=""></a>  <span class="fu">coord_quickmap</span>()</span>
<span id="cb3-8"><a href=""></a></span>
<span id="cb3-9"><a href=""></a>p1 <span class="sc">|</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"></section>
<section class="slide level2">

<p><strong><code>coord_quickmap()</code></strong></p>
<p>Both plots call <code>coord_quickmap()</code>, which adjusts the plot’s aspect ratio so that one degree of longitude and one degree of latitude occupy equal lengths on the page. Without this correction the map is geometrically distorted — stretched horizontally near the equator or compressed at higher latitudes.</p>
<p><code>coord_quickmap()</code> is a fast linear approximation. For high-accuracy mapping — especially large regions, polar areas, or published cartographic products — the <code>geom_sf()</code> / <code>coord_sf()</code> workflow (Section 6.2) provides a rigorous solution based on proper map projections.</p>
</section></section>
<section>
<section id="simple-features-maps" class="title-slide slide level1 center">
<h1>Simple features maps</h1>

</section>
<section id="simple-features-maps-1" class="slide level2">
<h2>Simple features maps</h2>
<p>The polygon approach works for quick visualisations, but it has real limitations. In practice, vector geospatial data is distributed in the <strong>simple features</strong> format, an international standard published by the Open Geospatial Consortium (OGC). The <code>sf</code> package (Pebesma 2018) is the canonical R implementation of this standard.</p>
<p>ggplot2 integrates with <code>sf</code> through two dedicated functions:</p>
<ul>
<li><code>geom_sf()</code> — renders sf geometries (points, lines, polygons, multipolygons, …).</li>
<li><code>coord_sf()</code> — controls the coordinate reference system (CRS) applied to the entire plot.</li>
</ul>
</section>
<section class="slide level2">

<p><strong>The <code>ozmaps</code> package</strong></p>
<p>The following examples use the <code>ozmaps</code> package (Sumner 2019), which bundles sf datasets for Australian administrative and electoral boundaries. We begin by inspecting the <code>ozmap_states</code> object, which contains the borders of all Australian states and territories:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">library</span>(ozmaps)</span>
<span id="cb4-2"><a href=""></a><span class="fu">library</span>(sf)</span>
<span id="cb4-3"><a href=""></a></span>
<span id="cb4-4"><a href=""></a>oz_states <span class="ot">&lt;-</span> ozmaps<span class="sc">::</span>ozmap_states</span>
<span id="cb4-5"><a href=""></a>oz_states</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 9 features and 1 field
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 105.5507 ymin: -43.63203 xmax: 167.9969 ymax: -9.229287
Geodetic CRS:  GDA94
# A tibble: 9 × 2
  NAME                                                                  geometry
* &lt;chr&gt;                                                       &lt;MULTIPOLYGON [°]&gt;
1 New South Wales              (((150.7016 -35.12286, 150.6611 -35.11782, 150.6…
2 Victoria                     (((146.6196 -38.70196, 146.6721 -38.70259, 146.6…
3 Queensland                   (((148.8473 -20.3457, 148.8722 -20.37575, 148.85…
4 South Australia              (((137.3481 -34.48242, 137.3749 -34.46885, 137.3…
5 Western Australia            (((126.3868 -14.01168, 126.3625 -13.98264, 126.3…
6 Tasmania                     (((147.8397 -40.29844, 147.8902 -40.30258, 147.8…
7 Northern Territory           (((136.3669 -13.84237, 136.3339 -13.83922, 136.3…
8 Australian Capital Territory (((149.2317 -35.222, 149.2346 -35.24047, 149.271…
9 Other Territories            (((167.9333 -29.05421, 167.9188 -29.0344, 167.93…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Structure of an sf tibble</strong></p>
<p>In contrast to the row-per-vertex layout of the polygon approach, each row in an sf tibble represents <strong>one complete geographic unit</strong>. The special <code>geometry</code> column stores the full polygon definition — potentially a <code>MULTIPOLYGON</code> assembled from several non-contiguous polygons — for each row.</p>
<p>The metadata printed above the tibble (geometry type, bounding box, geodetic CRS) is embedded directly in the sf object and does not need to be managed separately by the analyst.</p>
</section>
<section class="slide level2">

<p><strong>Drawing a minimal map with <code>geom_sf()</code></strong></p>
<p>Because <code>geom_sf()</code> automatically detects a column named <code>geometry</code>, no aesthetic mapping needs to be supplied:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="fu">ggplot</span>(oz_states) <span class="sc">+</span></span>
<span id="cb6-2"><a href=""></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href=""></a>  <span class="fu">coord_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section class="slide level2">

<p><strong>How <code>geom_sf()</code> resolves the geometry aesthetic</strong></p>
<p><code>geom_sf()</code> relies on an internal <code>geometry</code> aesthetic not used by any other geom. It is resolved by one of three mechanisms, in priority order:</p>
<ol type="1">
<li><strong>Implicit</strong> — when no mapping is given and the sf object contains a column named <code>geometry</code>, it is used automatically (as above).</li>
<li><strong>Auto-detect</strong> — if the data is an sf object, <code>geom_sf()</code> will find the geometry column regardless of its name.</li>
<li><strong>Explicit</strong> — you can always write <code>aes(geometry = my_column)</code> to specify the column directly. This is essential when a data frame contains multiple geometry columns.</li>
</ol>
<p><code>coord_sf()</code> handles the map projection; its role is discussed fully in Section 6.3.</p>
</section>
<section id="layered-maps" class="slide level2">
<h2>Layered maps</h2>
<p>ggplot2 supports stacking multiple <code>geom_sf()</code> layers to overlay datasets with different levels of geographic detail. The example below draws Australian state boundaries filled with distinct colours, then overlays simplified federal electoral boundaries on top.</p>
<p>Two pre-processing steps are required first:</p>
<ul>
<li><strong>Filter</strong> — “Other Territories” is removed from <code>oz_states</code> via <code>dplyr::filter()</code>, as it spans a large offshore region that distorts the map.</li>
<li><strong>Simplify</strong> — <code>rmapshaper::ms_simplify()</code> reduces the resolution of the electoral boundary data (<code>ozmaps::abs_ced</code>) to match the scale of the final plot, substantially speeding up rendering.</li>
</ul>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">library</span>(rmapshaper)</span>
<span id="cb7-2"><a href=""></a></span>
<span id="cb7-3"><a href=""></a>oz_states <span class="ot">&lt;-</span> ozmaps<span class="sc">::</span>ozmap_states <span class="sc">|&gt;</span> <span class="fu">filter</span>(NAME <span class="sc">!=</span> <span class="st">"Other Territories"</span>)</span>
<span id="cb7-4"><a href=""></a>oz_votes  <span class="ot">&lt;-</span> <span class="fu">ms_simplify</span>(ozmaps<span class="sc">::</span>abs_ced)</span>
<span id="cb7-5"><a href=""></a></span>
<span id="cb7-6"><a href=""></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb7-7"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> oz_states, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> NAME), <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb7-8"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> oz_votes, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href=""></a>  <span class="fu">coord_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section class="slide level2">

<p>The <code>fill = NAME</code> mapping assigns a distinct colour to each state. Although <code>NAME</code> conveys no quantitative information here, the same pattern generalises to any area-level variable: replacing <code>NAME</code> with a column such as <code>unemployment_rate</code> would produce a choropleth map. Note that when different layers draw from different data frames, the <code>data =</code> argument is specified inside each individual <code>geom_sf()</code> call, and <code>ggplot()</code> is left without a default dataset.</p>
</section>
<section id="labelled-maps" class="slide level2">
<h2>Labelled maps</h2>
<p>Text labels can be placed on sf maps using two geoms:</p>
<ul>
<li><code>geom_sf_label()</code> — renders labels inside a rectangular background box (suitable when labels must stand out against complex map backgrounds).</li>
<li><code>geom_sf_text()</code> — renders plain text with no box.</li>
</ul>
<p>Both functions use <code>sf::st_point_on_surface()</code> internally to compute an anchor point that is guaranteed to lie within each polygon.</p>
<p>The example below zooms into the Sydney metropolitan region and labels each federal electorate:</p>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>sydney_map <span class="ot">&lt;-</span> ozmaps<span class="sc">::</span>abs_ced <span class="sc">|&gt;</span> <span class="fu">filter</span>(NAME <span class="sc">%in%</span> <span class="fu">c</span>(</span>
<span id="cb8-2"><a href=""></a>  <span class="st">"Sydney"</span>, <span class="st">"Wentworth"</span>, <span class="st">"Warringah"</span>, <span class="st">"Kingsford Smith"</span>, <span class="st">"Grayndler"</span>, <span class="st">"Lowe"</span>,</span>
<span id="cb8-3"><a href=""></a>  <span class="st">"North Sydney"</span>, <span class="st">"Barton"</span>, <span class="st">"Bradfield"</span>, <span class="st">"Banks"</span>, <span class="st">"Blaxland"</span>, <span class="st">"Reid"</span>,</span>
<span id="cb8-4"><a href=""></a>  <span class="st">"Watson"</span>, <span class="st">"Fowler"</span>, <span class="st">"Werriwa"</span>, <span class="st">"Prospect"</span>, <span class="st">"Parramatta"</span>, <span class="st">"Bennelong"</span>,</span>
<span id="cb8-5"><a href=""></a>  <span class="st">"Mackellar"</span>, <span class="st">"Greenway"</span>, <span class="st">"Mitchell"</span>, <span class="st">"Chifley"</span>, <span class="st">"McMahon"</span></span>
<span id="cb8-6"><a href=""></a>))</span>
<span id="cb8-7"><a href=""></a></span>
<span id="cb8-8"><a href=""></a><span class="fu">ggplot</span>(sydney_map) <span class="sc">+</span></span>
<span id="cb8-9"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> NAME), <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href=""></a>  <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">150.97</span>, <span class="fl">151.3</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">33.98</span>, <span class="sc">-</span><span class="fl">33.79</span>)) <span class="sc">+</span></span>
<span id="cb8-11"><a href=""></a>  <span class="fu">geom_sf_label</span>(<span class="fu">aes</span>(<span class="at">label =</span> NAME), <span class="at">label.padding =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">"mm"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section class="slide level2">

<p><strong>Warning: <code>st_point_on_surface</code> with longitude–latitude data</strong></p>
<p>Running this code triggers a warning indicating that results may be incorrect for longitude–latitude coordinates. The warning arises because many sf geometric algorithms assume a flat Cartesian plane, whereas longitude–latitude data sits on an ellipsoidal surface. For moderate-scale maps at non-polar latitudes, the approximation is typically acceptable. For continent-scale maps or regions near the poles, the data should be reprojected to a planar CRS before labelling.</p>
</section>
<section id="adding-other-geoms" class="slide level2">
<h2>Adding other geoms</h2>
<p><code>geom_sf()</code> behaves like any other ggplot2 layer and can be freely combined with standard geoms. Provided that coordinates are supplied in the same spatial reference frame as the sf layers, <code>geom_point()</code>, <code>geom_text()</code>, and other geoms work as expected.</p>
<p>The code below overlays the locations of Australian capital cities — stored as a plain tibble of longitude–latitude values — onto the electoral map using <code>geom_point()</code>:</p>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>oz_capitals <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb9-2"><a href=""></a>  <span class="sc">~</span>city,        <span class="sc">~</span>lat,      <span class="sc">~</span>lon,</span>
<span id="cb9-3"><a href=""></a>  <span class="st">"Sydney"</span>,    <span class="sc">-</span><span class="fl">33.8688</span>,  <span class="fl">151.2093</span>,</span>
<span id="cb9-4"><a href=""></a>  <span class="st">"Melbourne"</span>, <span class="sc">-</span><span class="fl">37.8136</span>,  <span class="fl">144.9631</span>,</span>
<span id="cb9-5"><a href=""></a>  <span class="st">"Brisbane"</span>,  <span class="sc">-</span><span class="fl">27.4698</span>,  <span class="fl">153.0251</span>,</span>
<span id="cb9-6"><a href=""></a>  <span class="st">"Adelaide"</span>,  <span class="sc">-</span><span class="fl">34.9285</span>,  <span class="fl">138.6007</span>,</span>
<span id="cb9-7"><a href=""></a>  <span class="st">"Perth"</span>,     <span class="sc">-</span><span class="fl">31.9505</span>,  <span class="fl">115.8605</span>,</span>
<span id="cb9-8"><a href=""></a>  <span class="st">"Hobart"</span>,    <span class="sc">-</span><span class="fl">42.8821</span>,  <span class="fl">147.3272</span>,</span>
<span id="cb9-9"><a href=""></a>  <span class="st">"Canberra"</span>,  <span class="sc">-</span><span class="fl">35.2809</span>,  <span class="fl">149.1300</span>,</span>
<span id="cb9-10"><a href=""></a>  <span class="st">"Darwin"</span>,    <span class="sc">-</span><span class="fl">12.4634</span>,  <span class="fl">130.8456</span></span>
<span id="cb9-11"><a href=""></a>)</span>
<span id="cb9-12"><a href=""></a></span>
<span id="cb9-13"><a href=""></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb9-14"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> oz_votes) <span class="sc">+</span></span>
<span id="cb9-15"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> oz_states, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb9-16"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> oz_capitals, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> lon, <span class="at">y =</span> lat), <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-17"><a href=""></a>  <span class="fu">coord_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section class="slide level2">

<p>Any aesthetic available in <code>geom_point()</code> can encode additional metadata. For instance, if <code>oz_capitals</code> contained a column recording the number of federal electorates within each metropolitan area, mapping that column to <code>size</code> would produce a proportional symbol map overlaid on the electoral boundaries.</p>
</section></section>
<section>
<section id="map-projections" class="title-slide slide level1 center">
<h1>Map projections</h1>

</section>
<section id="map-projections-1" class="slide level2">
<h2>Map projections</h2>
<p>Treating longitude and latitude as ordinary Cartesian axes is a convenient simplification at small scales, but it becomes geometrically inaccurate at larger scales due to two fundamental problems.</p>
</section>
<section class="slide level2">

<p><strong>Problem 1 — The shape of the Earth</strong></p>
<p>The Earth is an oblate spheroid, not a flat plane or a perfect sphere. Mapping a coordinate pair (longitude, latitude) to a precise physical location therefore requires a set of geometric assumptions. This collection of assumptions — the shape of the reference ellipsoid, the position of the polar axis, the definition of sea level, and the location of the prime meridian — is called the <strong>geodetic datum</strong>.</p>
<p>Two commonly used datums are:</p>
<ul>
<li><strong>NAD83</strong> (North American Datum 1983) — well-calibrated for North America.</li>
<li><strong>WGS84</strong> (World Geodetic System 1984) — the global standard used by GPS receivers and most modern geospatial datasets.</li>
</ul>
<p>The same longitude–latitude pair can correspond to physically different locations under different datums — a discrepancy that can exceed many metres in some regions.</p>
</section>
<section class="slide level2">

<p><strong>Problem 2 — Projecting an ellipsoid onto a plane</strong></p>
<p>A printed or on-screen map is inherently two-dimensional, yet the Earth’s surface is curved. Any method of “unrolling” an ellipsoidal surface onto a plane inevitably introduces distortion. The <strong>map projection</strong> defines which geometric properties are preserved and which are sacrificed.</p>
<p>Two frequently cited projection families are:</p>
<ul>
<li><strong>Equal-area projections</strong> — regions of equal area on the globe occupy equal area on the map. Local shapes may appear distorted.</li>
<li><strong>Conformal projections</strong> — local shapes are preserved (angles are correct at every point). Area is distorted, often severely at high latitudes (the Mercator projection is the most familiar example).</li>
</ul>
<p>No single projection can simultaneously preserve both area and shape — the analyst must choose a projection that is appropriate for the intended use of the map.</p>
</section>
<section class="slide level2">

<p><strong>Coordinate Reference Systems (CRS)</strong></p>
<p>A <strong>coordinate reference system (CRS)</strong> is the complete specification of how geographic coordinates are translated into a 2D map. It combines:</p>
<ol type="1">
<li>The geodetic datum.</li>
<li>The projection type (e.g., Mercator, Lambert Conformal Conic, Albers Equal-Area).</li>
<li>The projection parameters (origin, standard parallels, false easting/northing, units).</li>
</ol>
</section>
<section class="slide level2">

<p>An sf object stores its CRS as embedded metadata, accessible via <code>sf::st_crs()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">st_crs</span>(oz_votes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4283 
  wkt:
GEOGCRS["GDA94",
    DATUM["Geocentric Datum of Australia 1994",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["Australia including Lord Howe Island, Macquarie Islands, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore."],
        BBOX[-60.56,93.41,-8.47,173.35]],
    ID["EPSG",4283]]</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>The verbose <strong>well-known text (WKT)</strong> string printed above unambiguously describes the CRS. A far more compact representation is the <strong>EPSG code</strong> — a unique integer assigned by the EPSG Geodetic Parameter Dataset (<a href="https://epsg.org" class="uri">https://epsg.org</a>). The default CRS for <code>oz_votes</code> corresponds to EPSG 4283 (GDA94):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="fu">st_crs</span>(oz_votes) <span class="sc">==</span> <span class="fu">st_crs</span>(<span class="dv">4283</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Changing the projection with <code>coord_sf()</code></strong></p>
<p><code>coord_sf()</code> controls the CRS applied to the entire plot. By default it adopts the CRS of the first sf layer. To override this, supply a valid CRS to the <code>crs</code> argument:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(oz_votes) <span class="sc">+</span> <span class="fu">geom_sf</span>()</span>
<span id="cb14-2"><a href=""></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(oz_votes) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span> <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="fu">st_crs</span>(<span class="dv">3112</span>))</span>
<span id="cb14-3"><a href=""></a>p1 <span class="sc">|</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section class="slide level2">

<p>EPSG 3112 is the GDA94 / Geoscience Australia Lambert projection, which minimises area distortion across the Australian continent. The difference in outline shape between the two panels illustrates how substantially the visual impression of a map can change with the choice of projection.</p>
<p>For a thorough treatment of map projections in R, see <em>Geocomputation with R</em> (<a href="https://geocompr.robinlovelace.net/" class="uri">https://geocompr.robinlovelace.net/</a>).</p>
</section></section>
<section>
<section id="working-with-sf-data" class="title-slide slide level1 center">
<h1>Working with sf data</h1>

</section>
<section id="working-with-sf-data-1" class="slide level2">
<h2>Working with sf data</h2>
<p>Beyond plotting, the <code>sf</code> package provides a rich set of functions for inspecting and transforming spatial objects. This section introduces the most commonly needed tools; full documentation is available at <a href="https://r-spatial.github.io/sf/" class="uri">https://r-spatial.github.io/sf/</a>.</p>
</section>
<section class="slide level2">

<p><strong>Motivation: complex geographic units</strong></p>
<p>A key advantage of the simple features format is its ability to represent <strong>geometrically complex</strong> regions in a single row. A <code>MULTIPOLYGON</code> geometry encodes a collection of non-contiguous polygons, which naturally models regions such as archipelagos or territories with enclaves.</p>
<p>The Eden-Monaro federal electorate in New South Wales is a good illustration. It consists of: (1) a large mainland polygon with a hole in the middle (the Australian Capital Territory is a distinct political unit entirely enclosed within Eden-Monaro, and electoral boundaries do not cross state lines), and (2) a small separate island. Both panels below are produced from a single row of sf data:</p>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>edenmonaro <span class="ot">&lt;-</span> ozmaps<span class="sc">::</span>abs_ced <span class="sc">|&gt;</span> <span class="fu">filter</span>(NAME <span class="sc">==</span> <span class="st">"Eden-Monaro"</span>)</span>
<span id="cb15-2"><a href=""></a></span>
<span id="cb15-3"><a href=""></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(edenmonaro) <span class="sc">+</span> <span class="fu">geom_sf</span>()</span>
<span id="cb15-4"><a href=""></a>p1 <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">147.75</span>, <span class="fl">150.25</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">37.5</span>, <span class="sc">-</span><span class="fl">34.5</span>))</span>
<span id="cb15-5"><a href=""></a>p2 <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">150</span>, <span class="fl">150.25</span>),    <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">36.3</span>, <span class="sc">-</span><span class="dv">36</span>))</span>
<span id="cb15-6"><a href=""></a>p1 <span class="sc">|</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"></section>
<section class="slide level2">

<p><strong>Extracting the geometry column</strong></p>
<p>The geometry column can be isolated as a standalone <code>sfc</code> (simple feature column) object using <code>dplyr::pull()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a>edenmonaro <span class="ot">&lt;-</span> edenmonaro <span class="sc">|&gt;</span> <span class="fu">pull</span>(geometry)</span>
<span id="cb16-2"><a href=""></a>edenmonaro</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 1 feature 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 147.6874 ymin: -37.50503 xmax: 150.2307 ymax: -34.53558
Geodetic CRS:  GDA94</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Metadata helper functions</strong></p>
<p>Several <code>sf</code> functions extract metadata from a geometry object:</p>
<ul>
<li><code>st_geometry_type()</code> — returns the geometry type (e.g., <code>MULTIPOLYGON</code>, <code>POLYGON</code>, <code>LINESTRING</code>, <code>POINT</code>).</li>
<li><code>st_dimension()</code> — returns the spatial dimension count: 2 for XY data, 3 for XYZ.</li>
<li><code>st_bbox()</code> — returns the bounding box as a named numeric vector (<code>xmin</code>, <code>ymin</code>, <code>xmax</code>, <code>ymax</code>).</li>
<li><code>st_crs()</code> — returns the coordinate reference system as a list containing the EPSG code and a WKT string.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="fu">st_bbox</span>(edenmonaro)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     xmin      ymin      xmax      ymax 
147.68741 -37.50503 150.23068 -34.53558 </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Casting between geometry types with <code>st_cast()</code></strong></p>
<p>A <code>MULTIPOLYGON</code> can be decomposed into its constituent <code>POLYGON</code> objects using <code>st_cast()</code>. For Eden-Monaro, this reveals the two distinct polygons that make up the electorate:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a><span class="fu">st_cast</span>(edenmonaro, <span class="st">"POLYGON"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 2 features 
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 147.6874 ymin: -37.50503 xmax: 150.2307 ymax: -34.53558
Geodetic CRS:  GDA94</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Practical application: isolating islands</strong></p>
<p>The Dawson electorate in Queensland comprises 69 offshore islands plus one large coastal mainland region — 70 polygon components in total:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a>dawson <span class="ot">&lt;-</span> ozmaps<span class="sc">::</span>abs_ced <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href=""></a>  <span class="fu">filter</span>(NAME <span class="sc">==</span> <span class="st">"Dawson"</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href=""></a>  <span class="fu">pull</span>(geometry)</span>
<span id="cb22-4"><a href=""></a></span>
<span id="cb22-5"><a href=""></a><span class="fu">ggplot</span>(dawson) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span> <span class="fu">coord_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-15-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"></section>
<section class="slide level2">

<p>To map only the islands, cast to individual polygons, compute each polygon’s area with <code>st_area()</code>, identify the largest polygon (the mainland) with <code>which.max()</code>, and exclude it by negative indexing:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a>dawson <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(dawson, <span class="st">"POLYGON"</span>)</span>
<span id="cb23-2"><a href=""></a><span class="fu">which.max</span>(<span class="fu">st_area</span>(dawson))  <span class="co"># Mainland is polygon 69</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 69</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a><span class="fu">ggplot</span>(dawson[<span class="sc">-</span><span class="dv">69</span>]) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span> <span class="fu">coord_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-16-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"><p>This cast → measure → subset workflow generalises to any situation where the geographic components of a region must be treated independently — for example, separating mainland from island territories, or identifying the largest contiguous region within a complex multipolygon.</p>
</section></section>
<section>
<section id="raster-maps" class="title-slide slide level1 center">
<h1>Raster maps</h1>

</section>
<section id="raster-maps-1" class="slide level2">
<h2>Raster maps</h2>
<p>In addition to vector-based simple features, geospatial information is commonly stored as <strong>raster data</strong>: a regular rectangular grid of cells (pixels) where each cell holds one or more numeric values. Rasters are the natural format for satellite imagery, digital elevation models, land cover classifications, and gridded climate datasets.</p>
<p>Many raster file formats — most notably <strong>GeoTIFF</strong> — embed spatial metadata (geodetic datum, CRS, spatial extent, pixel size) that allows the image to be accurately positioned on the Earth’s surface. R can read these formats via GDAL (Geospatial Data Abstraction Library, <a href="https://gdal.org/" class="uri">https://gdal.org/</a>), which the <code>sf</code> package exposes through <code>sf::gdal_read()</code>. In practice, higher-level packages handle this transparently.</p>
</section>
<section class="slide level2">

<p><strong>Reading raster data with the <code>stars</code> package</strong></p>
<p>The <code>stars</code> package (Pebesma 2020) provides tools for reading and manipulating spatiotemporal raster arrays. The example below imports a GeoTIFF file containing a visible-light satellite image captured by the Himawari-8 geostationary satellite and originally sourced from the Australian Bureau of Meteorology.</p>
<p>The <code>RasterIO</code> list is passed directly to GDAL: <code>nBufXSize</code> and <code>nBufYSize</code> downsample the image to 600 × 600 pixels on import, reducing memory usage while retaining enough detail for visualisation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">library</span>(stars)</span>
<span id="cb26-2"><a href=""></a></span>
<span id="cb26-3"><a href=""></a>sat_vis <span class="ot">&lt;-</span> <span class="fu">read_stars</span>(</span>
<span id="cb26-4"><a href=""></a>  <span class="fu">paste0</span>(<span class="st">"https://raw.githubusercontent.com/hadley/"</span>,</span>
<span id="cb26-5"><a href=""></a>  <span class="st">"ggplot2-book/main/IDE00422.202001072100.tif"</span>),</span>
<span id="cb26-6"><a href=""></a>  <span class="at">RasterIO =</span> <span class="fu">list</span>(<span class="at">nBufXSize =</span> <span class="dv">600</span>, <span class="at">nBufYSize =</span> <span class="dv">600</span>)</span>
<span id="cb26-7"><a href=""></a>)</span>
<span id="cb26-8"><a href=""></a>sat_vis</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>stars object with 3 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
                           Min. 1st Qu. Median     Mean 3rd Qu. Max.
IDE00422.202001072100.tif     0       0      0 18.12981       0  255
dimension(s):
     from  to   offset  delta                  refsys point x/y
x       1 600 -5500000  18333 Geostationary_Satellite FALSE [x]
y       1 600  5500000 -18333 Geostationary_Satellite FALSE [y]
band    1   3       NA     NA                      NA    NA    </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p><strong>Structure of a <code>stars</code> object</strong></p>
<p>A <code>stars</code> object is an n-dimensional labelled array. For this satellite image, the three dimensions are:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Dimension</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>x</code></td>
<td>Columns (east–west), associated with a CRS</td>
</tr>
<tr class="even">
<td><code>y</code></td>
<td>Rows (north–south), associated with a CRS</td>
</tr>
<tr class="odd">
<td><code>band</code></td>
<td>Colour channel: 1 = Red, 2 = Green, 3 = Blue</td>
</tr>
</tbody>
</table>
<p>Since the image is greyscale, all three bands carry identical values. More complex datasets may include a <code>time</code> dimension (multi-temporal composites) or additional bands (hyperspectral sensors). The CRS for each spatial dimension is stored alongside the data.</p>
</section>
<section class="slide level2">

<p><strong>Plotting raster data with <code>geom_stars()</code></strong></p>
<p><code>geom_stars()</code>, provided by the <code>stars</code> package, maps raster pixel values to the <code>fill</code> aesthetic. A minimal plot applies ggplot2’s default sequential blue scale to the raw 0–255 pixel values:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="fu">library</span>(stars)</span>
<span id="cb28-2"><a href=""></a></span>
<span id="cb28-3"><a href=""></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href=""></a>  <span class="fu">geom_stars</span>(<span class="at">data =</span> sat_vis) <span class="sc">+</span></span>
<span id="cb28-5"><a href=""></a>  <span class="fu">coord_equal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-18-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"><p>The blue colouring reflects the ggplot2 scale choice rather than the original image appearance. To display the image in greyscale — a more faithful representation of visible-light satellite imagery — apply <code>scale_fill_gradient(low = "black", high = "white")</code>.</p>
</section>
<section class="slide level2">

<p><strong>Separating bands with <code>facet_wrap()</code></strong></p>
<p>Because <code>sat_vis</code> contains three bands, they can be displayed in separate panels using <code>facet_wrap()</code>. For a greyscale image, all three panels will be identical; for a multi-spectral image, the panels would reveal the spatial pattern captured by each sensor:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb29-2"><a href=""></a>  <span class="fu">geom_stars</span>(<span class="at">data =</span> sat_vis, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href=""></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(band)) <span class="sc">+</span></span>
<span id="cb29-4"><a href=""></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb29-5"><a href=""></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"black"</span>, <span class="at">high =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-19-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"></section>
<section class="slide level2">

<p><strong>Reprojecting vector data to match a raster CRS</strong></p>
<p>Without reprojection, overlaying <code>oz_states</code> (EPSG 4283) on <code>sat_vis</code> (geostationary projection) would misalign the layers. <code>sf::st_transform()</code> reprojects the vector data to match the raster’s CRS:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a>oz_states <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(oz_states, <span class="at">crs =</span> <span class="fu">st_crs</span>(sat_vis))</span>
<span id="cb30-2"><a href=""></a></span>
<span id="cb30-3"><a href=""></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb30-4"><a href=""></a>  <span class="fu">geom_stars</span>(<span class="at">data =</span> sat_vis, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> oz_states, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href=""></a>  <span class="fu">coord_sf</span>() <span class="sc">+</span></span>
<span id="cb30-7"><a href=""></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb30-8"><a href=""></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"black"</span>, <span class="at">high =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-20-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"><p>With correctly reprojected state boundaries, the white outlines align precisely with the coastlines visible in the satellite image.</p>
</section>
<section class="slide level2">

<p><strong>Overlaying point data on a reprojected raster</strong></p>
<p>Tabular point data (longitude–latitude columns in a plain data frame) must also be transformed before overlaying on a reprojected raster. The required two-step workflow is:</p>
<ol type="1">
<li>Convert to an sf object with <code>st_as_sf()</code>, specifying the source CRS as WGS84 (EPSG 4326).</li>
<li>Reproject to the raster CRS with <code>st_transform()</code>.</li>
</ol>
</section>
<section class="slide level2">

<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a>cities <span class="ot">&lt;-</span> oz_capitals <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href=""></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"lon"</span>, <span class="st">"lat"</span>), <span class="at">crs =</span> <span class="dv">4326</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>)</span>
<span id="cb31-3"><a href=""></a></span>
<span id="cb31-4"><a href=""></a>cities <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(cities, <span class="fu">st_crs</span>(sat_vis))</span>
<span id="cb31-5"><a href=""></a></span>
<span id="cb31-6"><a href=""></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb31-7"><a href=""></a>  <span class="fu">geom_stars</span>(<span class="at">data =</span> sat_vis, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> oz_states, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb31-9"><a href=""></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> cities, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb31-10"><a href=""></a>  <span class="fu">coord_sf</span>() <span class="sc">+</span></span>
<span id="cb31-11"><a href=""></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb31-12"><a href=""></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"black"</span>, <span class="at">high =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch6_files/figure-revealjs/unnamed-chunk-21-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"></section>
<section class="slide level2">

<p><strong>Interpreting the composite map</strong></p>
<p>With capital city locations correctly projected onto the satellite image, it becomes apparent that the image was taken at approximately sunrise in Darwin: eastern capitals (Sydney, Melbourne, Brisbane, Canberra) lie in the illuminated zone, while Perth in the west remains in darkness. City names can be added with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a><span class="fu">geom_sf_text</span>(<span class="at">data =</span> cities, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">label =</span> city))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>mapping: label = ~city 
geom_text: parse = FALSE, check_overlap = FALSE, na.rm = FALSE
stat_sf_coordinates: na.rm = FALSE, fun.geometry = NULL
position_nudge </code></pre>
</div>
</div>
<p>Some label positioning adjustment would be needed to prevent overlap (see Chapter 8 on annotations).</p>
<p><strong>Note on interactive 3D maps:</strong> For true perspective-view or rotatable 3D surface visualisations beyond ggplot2’s scope, the <code>rgl</code> package (<a href="http://rgl.neoscientists.org" class="uri">http://rgl.neoscientists.org</a>) is the standard tool.</p>
</section></section>
<section>
<section id="data-sources" class="title-slide slide level1 center">
<h1>Data sources</h1>

</section>
<section id="data-sources-1" class="slide level2">
<h2>Data sources</h2>
<p>A wide variety of R packages provide ready-to-use geospatial datasets for use with <code>geom_sf()</code> and related tools:</p>
</section>
<section class="slide level2">

<p><strong>US-focused data</strong></p>
<ul>
<li><p><strong>USAboundaries</strong> (<a href="https://github.com/ropensci/USAboundaries" class="uri">https://github.com/ropensci/USAboundaries</a>) — state, county, and ZIP code boundaries for the contiguous United States, plus historical boundaries extending back to the 1600s (Mullen &amp; Bratt 2018).</p></li>
<li><p><strong>tigris</strong> (<a href="https://github.com/walkerke/tigris" class="uri">https://github.com/walkerke/tigris</a>) — downloads US Census Bureau TIGER/Line shapefiles on demand. Provides state, county, ZIP code, and census tract boundaries, as well as roads, water bodies, and other geographic layers (Walker 2019).</p></li>
</ul>
</section>
<section class="slide level2">

<p><strong>Global data</strong></p>
<ul>
<li><p><strong>rnaturalearth</strong> (<a href="https://CRAN.R-project.org/package=rnaturalearth" class="uri">https://CRAN.R-project.org/package=rnaturalearth</a>) — wraps the Natural Earth project (<a href="https://naturalearthdata.com/" class="uri">https://naturalearthdata.com/</a>), a free, well-maintained global dataset. Includes country boundaries and first-level administrative subdivisions (states, provinces, regions, counties) for every country (South 2017).</p></li>
<li><p><strong>osmar</strong> (<a href="https://cran.r-project.org/package=osmar" class="uri">https://cran.r-project.org/package=osmar</a>) — interfaces with the OpenStreetMap API to retrieve granular vector data: individual streets, buildings, parks, and points of interest at the city block level (Eugster &amp; Schlesinger 2010).</p></li>
</ul>
</section>
<section class="slide level2">

<p><strong>Working with your own shapefiles</strong></p>
<p>If geospatial data are already available locally in ESRI Shapefile format (<code>.shp</code>), they can be imported directly into R as an sf object with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a>my_map <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">read_sf</span>(<span class="st">"path/to/my_shapefile.shp"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Once loaded, the object is fully compatible with <code>geom_sf()</code>, <code>coord_sf()</code>, and all other sf-aware functions covered in this chapter.</p>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials have been adapted from <a href="https://ggplot2-book.org/maps.html"><strong>ggplot2: Elegant Graphics for Data Analysis (3e)</strong></a>. All rights are reserved by the original authors and publishers.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p><code>ggplot2</code>: Elegant Graphics for Data Analysis</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch6_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch6_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch6_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="ch6_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch6-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>