project:
  type: website
  output-dir: .

website:
  title: "Data Analysis"
  favicon: hex/da.svg
  navbar:
    logo: hex/da.svg
    left:
      - href: sylla.qmd
        text: Syllabus
      - href: slide.qmd
        text: Slides
      - href: prob.qmd
        text: Problem sets
      - href: r.qmd
        text: R

format:
  html:
    theme:
      - Minty
      - brand
    # css: styles.css 
    toc: true
    toc-depth: 3

editor: source

# quarto rende