project:
  type: website
  output-dir: ../

website:
  title: "Data Aanlysis"
  navbar:
    left:
      - href: slide.qmd
        text: Slides
      - href: prob.qmd
        text: Problem sets

format:
  html:
    theme:
      - Minty
      - brand
    css: styles.css
    toc: true

editor: visual

# quarto render -- no-clean



